
sudo: false
language: ruby
env:
  - ES_IMAGE=elasticsearch:1
  - ES_IMAGE=elasticsearch:2.0
  - ES_IMAGE=elasticsearch:5.4
  - ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:6.3.0
rvm:
  - ruby-head
before_install:
  - docker-compose up -d
  - sleep 10
install:
  - travis_retry bundle install
script: rake test --trace

